name: swin
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0

  cupertino_icons: ^1.0.8
  onnxruntime: 1.4.1
  image: ^4.5.4
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.1
  image_picker: ^1.2.0
  rxdart: ^0.28.0
  shimmer_animation: ^2.2.2
  get_it: ^8.2.0
  path_provider: ^2.1.5
  flutter_html: ^3.0.0
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  firebase_crashlytics: ^5.0.6
  permission_handler: ^12.0.1
  logger: ^2.5.0
  carousel_slider: ^5.1.1
  shared_preferences: ^2.5.3
  dio: ^5.9.0
  chopper: ^8.4.0
  http: ^1.6.0
  url_launcher: ^6.3.2
  syncfusion_flutter_pdfviewer: ^31.1.19
  uvc_manager:
    path: D:\PTIT\DoAn\UVC4Flutter
#    git:
#      url: https://github.com/saki4510t/UVC4Flutter.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/models/
    - assets/images/
    - assets/pdfs/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"